services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/boardgameclub
      - ORIGIN=${ORIGIN:-http://damonpyo.mooo.com:8988}
      - BODY_SIZE_LIMIT=Infinity
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boardgameclub
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "8989:80"
      # - "443:443" # HTTPS disabled for custom port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - EMAIL=${EMAIL:-admin@localhost}
    depends_on:
      - app

volumes:
  db-data:
  caddy_data:
  caddy_config:
