use aes::Aes128;
use aes::cipher::{BlockEncrypt, KeyInit, generic_array::GenericArray};

/// AES-128-ECB encrypt a single 16-byte block
fn aes_ecb_encrypt(key: &[u8; 16], plaintext: &[u8; 16]) -> [u8; 16] {
    let cipher = Aes128::new(GenericArray::from_slice(key));
    let mut block = GenericArray::clone_from_slice(plaintext);
    cipher.encrypt_block(&mut block);
    block.into()
}

#[derive(Clone, Copy, PartialEq)]
enum Padding { Head, Tail }

#[derive(Clone, Copy, PartialEq)]
enum Order { Normal, Reverse }

/// Verify a single (hash, prand, key, padding, order) combination
fn verify_metric(
    hash: &[u8; 3],
    prand: &[u8; 3],
    key: &[u8; 16],
    padding: Padding,
    order: Order,
) -> bool {
    let mut plaintext = [0u8; 16];

    let (p0, p1, p2) = match order {
        Order::Normal => (prand[0], prand[1], prand[2]),
        Order::Reverse => (prand[2], prand[1], prand[0]),
    };

    match padding {
        Padding::Head => {
            plaintext[0] = p0;
            plaintext[1] = p1;
            plaintext[2] = p2;
        }
        Padding::Tail => {
            plaintext[13] = p0;
            plaintext[14] = p1;
            plaintext[15] = p2;
        }
    }

    let encrypted = aes_ecb_encrypt(key, &plaintext);

    match padding {
        Padding::Tail => {
            // Both Normal and Reverse check same bytes in the TS code
            encrypted[13] == hash[0] && encrypted[14] == hash[1] && encrypted[15] == hash[2]
        }
        Padding::Head => {
            match order {
                Order::Normal => {
                    encrypted[0] == hash[0] && encrypted[1] == hash[1] && encrypted[2] == hash[2]
                }
                Order::Reverse => {
                    // TS has two checks: normal order AND reversed hash
                    if encrypted[0] == hash[0] && encrypted[1] == hash[1] && encrypted[2] == hash[2] {
                        return true;
                    }
                    encrypted[0] == hash[2] && encrypted[1] == hash[1] && encrypted[2] == hash[0]
                }
            }
        }
    }
}

/// Parse a MAC address string (with or without colons) into 6 bytes
fn parse_mac(mac: &str) -> Option<[u8; 6]> {
    let clean: String = mac.replace(':', "");
    if clean.len() != 12 {
        return None;
    }
    let bytes = hex::decode(&clean).ok()?;
    let mut result = [0u8; 6];
    result.copy_from_slice(&bytes);
    Some(result)
}

/// Resolve a BLE RPA (Resolvable Private Address) against an IRK.
/// Returns true if the MAC was generated by the device with the given IRK.
///
/// Port of the TypeScript `resolveRPA` from src/lib/server/ble.ts lines 165-229.
pub fn resolve_rpa(mac: &str, irk_bytes: &[u8; 16], irk_bytes_rev: &[u8; 16]) -> bool {
    let mac_bytes = match parse_mac(mac) {
        Some(b) => b,
        None => return false,
    };

    // Two candidate interpretations of the 6 MAC bytes
    let candidates: [([u8; 3], [u8; 3]); 2] = [
        // candidate 1: first 3 = prand, last 3 = hash
        (
            [mac_bytes[0], mac_bytes[1], mac_bytes[2]],
            [mac_bytes[3], mac_bytes[4], mac_bytes[5]],
        ),
        // candidate 2: last 3 = prand, first 3 = hash
        (
            [mac_bytes[3], mac_bytes[4], mac_bytes[5]],
            [mac_bytes[0], mac_bytes[1], mac_bytes[2]],
        ),
    ];

    for (prand, hash) in &candidates {
        // Same 4 checks as the TypeScript code:
        // 1. key_rev, Tail, Normal
        if verify_metric(hash, prand, irk_bytes_rev, Padding::Tail, Order::Normal) {
            return true;
        }
        // 2. key_rev, Head, Reverse
        if verify_metric(hash, prand, irk_bytes_rev, Padding::Head, Order::Reverse) {
            return true;
        }
        // 3. key_std, Tail, Reverse
        if verify_metric(hash, prand, irk_bytes, Padding::Tail, Order::Reverse) {
            return true;
        }
        // 4. key_std, Tail, Normal
        if verify_metric(hash, prand, irk_bytes, Padding::Tail, Order::Normal) {
            return true;
        }
    }

    false
}

/// Pre-compute IRK bytes and reversed IRK bytes from hex string
pub fn parse_irk(irk_hex: &str) -> Option<([u8; 16], [u8; 16])> {
    let bytes = hex::decode(irk_hex).ok()?;
    if bytes.len() != 16 {
        return None;
    }
    let mut irk = [0u8; 16];
    irk.copy_from_slice(&bytes);

    let mut irk_rev = [0u8; 16];
    for (i, &b) in bytes.iter().enumerate() {
        irk_rev[15 - i] = b;
    }

    Some((irk, irk_rev))
}

#[cfg(test)]
mod tests {
    use super::*;

    // Test vectors generated by Node.js resolveRPA (verified to return true).
    // Generated using: keyRev + Tail + Normal combo.
    // MAC format: prand[0]:prand[1]:prand[2]:hash[0]:hash[1]:hash[2]
    const TEST_IRK: &str = "00112233445566778899aabbccddeeff";

    // These MACs were generated by Node.js and verified with the TS resolveRPA
    const TEST_VECTORS: &[(&str, &str)] = &[
        ("AB:CD:EF:B9:43:90", TEST_IRK),
        ("01:02:03:04:4B:69", TEST_IRK),
        ("FF:FE:FD:A0:7C:0E", TEST_IRK),
        ("12:34:56:F1:54:4D", TEST_IRK),
        ("AA:BB:CC:80:CE:4C", TEST_IRK),
    ];

    #[test]
    fn test_resolve_rpa_matching_vectors() {
        for (mac, irk_hex) in TEST_VECTORS {
            let (irk, irk_rev) = parse_irk(irk_hex).unwrap();
            assert!(
                resolve_rpa(mac, &irk, &irk_rev),
                "Should match: mac={}, irk={}",
                mac, irk_hex,
            );
        }
    }

    #[test]
    fn test_resolve_rpa_wrong_irk() {
        let wrong_irk_hex = "aabbccddeeff00112233445566778899";
        let (wrong_irk, wrong_irk_rev) = parse_irk(wrong_irk_hex).unwrap();

        for (mac, _) in TEST_VECTORS {
            assert!(
                !resolve_rpa(mac, &wrong_irk, &wrong_irk_rev),
                "Should NOT match wrong IRK for mac={}",
                mac,
            );
        }
    }

    #[test]
    fn test_resolve_rpa_invalid_mac() {
        let (irk, irk_rev) = parse_irk(TEST_IRK).unwrap();

        assert!(!resolve_rpa("invalid", &irk, &irk_rev));
        assert!(!resolve_rpa("", &irk, &irk_rev));
        assert!(!resolve_rpa("AA:BB:CC", &irk, &irk_rev));
        assert!(!resolve_rpa("ZZ:ZZ:ZZ:ZZ:ZZ:ZZ", &irk, &irk_rev));
    }

    #[test]
    fn test_resolve_rpa_random_mac_no_match() {
        let (irk, irk_rev) = parse_irk(TEST_IRK).unwrap();

        // Random MACs should not match
        assert!(!resolve_rpa("DE:AD:BE:EF:CA:FE", &irk, &irk_rev));
        assert!(!resolve_rpa("11:22:33:44:55:66", &irk, &irk_rev));
        assert!(!resolve_rpa("00:00:00:00:00:00", &irk, &irk_rev));
    }

    #[test]
    fn test_resolve_rpa_lowercase_mac() {
        let (irk, irk_rev) = parse_irk(TEST_IRK).unwrap();

        // Should work with lowercase MAC too
        assert!(resolve_rpa("ab:cd:ef:b9:43:90", &irk, &irk_rev));
    }

    #[test]
    fn test_resolve_rpa_no_colons() {
        let (irk, irk_rev) = parse_irk(TEST_IRK).unwrap();

        // Should work without colons
        assert!(resolve_rpa("ABCDEFB94390", &irk, &irk_rev));
    }

    #[test]
    fn test_parse_irk() {
        let (irk, irk_rev) = parse_irk("00112233445566778899aabbccddeeff").unwrap();
        assert_eq!(irk[0], 0x00);
        assert_eq!(irk[15], 0xFF);
        assert_eq!(irk_rev[0], 0xFF);
        assert_eq!(irk_rev[15], 0x00);

        assert!(parse_irk("invalid").is_none());
        assert!(parse_irk("0011").is_none());
        assert!(parse_irk("").is_none());
    }
}
